# Generated by Django 2.2.2 on 2019-07-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_img_url',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_more_info',
            new_name='more_info',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_views',
            new_name='views',
        ),
    ]
