# Generated by Django 2.2.3 on 2019-07-06 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190704_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
