# Generated by Django 2.2.3 on 2019-07-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_projects_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.CharField(default='url', max_length=40),
            preserve_default=False,
        ),
    ]
