# Generated by Django 2.2.3 on 2019-07-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190707_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='credits',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='installation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='license',
            field=models.CharField(max_length=200),
        ),
    ]
