# Generated by Django 2.2.3 on 2019-07-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190707_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='credits',
            field=models.TextField(),
        ),
    ]
