# Generated by Django 2.2.3 on 2019-08-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20190811_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='works',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='intro',
            field=models.CharField(max_length=150),
        ),
    ]
