# Generated by Django 2.2.3 on 2019-08-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20190811_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.TextField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
