# Generated by Django 2.2.3 on 2019-08-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20190811_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='source',
        ),
        migrations.AddField(
            model_name='project',
            name='homepage',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
