# Generated by Django 2.2.3 on 2019-08-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20190811_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='homepage_url',
        ),
        migrations.AddField(
            model_name='project',
            name='releases',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='releases_url',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='source_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
