# Generated by Django 2.2.3 on 2019-08-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20190811_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='release_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='releases',
            field=models.CharField(max_length=40),
        ),
    ]
