# Generated by Django 2.2.3 on 2019-08-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20190811_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='more_info',
            new_name='extra_info',
        ),
        migrations.AddField(
            model_name='project',
            name='get_started',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
