# Generated by Django 2.2.3 on 2019-08-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20190811_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='extra_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='homepage',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='installation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='releases',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
