# Generated by Django 2.2.3 on 2019-08-11 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20190811_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='extra_info',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='homepage',
            field=models.CharField(blank=True, default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='installation',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='releases',
            field=models.CharField(blank=True, default=11, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='source',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
