# Generated by Django 2.2.3 on 2019-08-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20190811_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_installation',
            field=models.BooleanField(default=False),
        ),
    ]
