# Generated by Django 2.2.3 on 2019-08-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_project_has_installation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='open_source',
            field=models.BooleanField(default=False),
        ),
    ]
