# Generated by Django 2.2.3 on 2019-08-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_project_open_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='release_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
