# Generated by Django 2.2.3 on 2019-08-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20190811_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='slug_name',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
