# Generated by Django 2.2.3 on 2019-08-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20190811_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('wip', 'wip'), ('code', 'code'), ('art', 'art'), ('fun', 'fun')], default='code', max_length=4),
        ),
    ]
