# Generated by Django 2.2.3 on 2019-08-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20190811_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='usage',
            field=models.TextField(blank=True),
        ),
    ]
