# Generated by Django 2.2.3 on 2019-08-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('maintained', 'maintained'), ('unmaintained', 'unmaintained')], default='maintained', max_length=12),
        ),
    ]
