# Generated by Django 2.2.3 on 2019-08-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
