# Generated by Django 2.2.3 on 2019-08-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_project_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='extra_info',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'web'), ('games', 'games'), ('plugins', 'plugins'), ('design', 'art & design'), ('deepshit', 'deepshit')], default='code', max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='intro',
            field=models.TextField(),
        ),
    ]
